### ISSUE TITLE
About optimisation: selection before sice.py

### ISSUE THREAD

**Issue by wehrad** [mankoff/SICE#12]
For the moment, full scenes that fall into the footprint area are processed and at the end, overlaps are checked based on SZA and cloud coverage to create a mosaic, if I'm not mistaken.
What about doing a basic and fast selection before sice.py, so that only the needed areas are processed (highest SZA if overlap)? Checking the SZA will be fast, one of the sice cloud cover computation could be added to combine with SZA (I heard Baptiste is/will be working on cloud masks optimisation). 
Even if it's about adding a step, I think the computation costs linked to it are way lower compared to what we can save afterwards. 

What do you think about it? If interesting, I can work on a proposition.

**Comment by mankoff** [comment]
I don't understand what you are proprosing. Select for highest SZA before sice? But what if there are clouds and we need to take the non-highest cloud-free SZA?

**Comment by wehrad** [comment]
The idea is to couple a highest SZA selection and a cloud coverage selection using one of the sice cloud masks (of course, this one wouldn't be computed again in sice afterwards). The result of this step would be a boolean mask (True=to process, False=ignore). Of course, this mask wouldn't be one  using sice outputs but S3Snow or native scenes.

**Comment by mankoff** [comment]
Ah - so you want to run sice 2x, once only where there are overlaps to find clouds (presumably a sice subset only to detect clouds?) and then the 2nd full time? I guess this may save time. I don't know. Sounds non-trivial.

**Comment by wehrad** [comment]
Actually this upstream selection as I imagine it would be independent of sice.
Check highest SZA (don't need sice for that) and determine a cloud coverage using a cloud mask independent of sice. For example, using a threshold on r_TOA band 21 (it's currently set to 0.77 if I remember well).
In that case, sice is run only once.

**Comment by mankoff** [comment]
Ok - both of your previous messages suggested using "one of the sice cloud [mask [or] cover computation]", suggesting running sice 2x. Running sice less makes more sense than running it more.

**Comment by wehrad** [comment]
Yes, sorry for this misunderstanding. More precisely, "one of the sice cloud cover" that isn't based on sice variables but S3Snow or native. In this way, we could just move it out of sice to compute it upstream and perform a coupled SZA/cloud selection, before sice.
So, do you think it's worth a try? Maybe it would be clearer if I provide example of implementation.
