### ISSUE TITLE
turn off cloud masking for t_TOA bands in mosaic step

### ISSUE THREAD

**Issue by jasonebox** [mankoff/SICE#40]
Currently r_TOA (OLCI r_TOA_01 .. r_TOA_21 and SLSTR r_TOA_S1 r_TOA_S5) mosaics have NaN values wherever clouds are identified. An improvement for Chung's Master's thesis (and other applications) would be not setting cloudy areas to NaN in r_TOA data. This masking happens near the end of the toolchain with Grass.

**Comment by BaptisteVandecrux** [comment]
Fixed by Adrien:
https://github.com/GEUS-SICE/SICE/blob/baf2244c630b5e49d5f17f2aab2925f25e734b93/dm.grass.sh#L65
