### ISSUE TITLE
how SICE.py loops over scenes?

### ISSUE THREAD

**Issue by jasonebox** [mankoff/SICE#6]
more detail seems needed in the readme.org to inform users how SICE.py (or a script that calls it?) loops over scenes.

In other words, Adrien can't find a script to loop over scenes?

cheers,

Jason

**Comment by wehrad** [comment]
My bad, this is actually in S3_wrapper.sh and specified in the readme. I was looking for a special wrapper just for SICE.py. Issue can be closed.
